fix: add upgrade step for missing stopwords registry entries
collective/collective.solr pull request #372
Opened 2024-02-05 22:01 UTC by remdub

Closes #371

2024-02-06 16:30 UTC, tisto commented on src/collective/solr/upgrades.zcml
> +    destination="8"
@remdub thanks for your contribution! The current number in metadata.xml is 7:

https://github.com/collective/collective.solr/blob/main/src/collective/solr/profiles/default/metadata.xml#L3

Don't we need to upgrade that number as well then?

2024-02-06 16:31 UTC, reebalazs approved these changes
Hmm ok thank you, I've missed this.

2024-02-06 16:34 UTC, reebalazs commented
@rendub can you please check the metadata issue that @tisto mentioned?

2024-02-06 16:36 UTC, reebalazs requested changes
pls check the metadata number in metadata.xml and test out if the upgrade is correct

2024-02-07 08:20 UTC, remdub commented
> pls check the metadata number in metadata.xml and test out if the upgrade is correct

Thank you. Done and tested !

> 2024-02-07 09:16:17,736 INFO    [collective.solr:144][waitress-3] Migrated to version 8
2024-02-07 09:16:17,736 INFO    [GenericSetup:1138][waitress-3] Ran upgrade step Upgrade to collective.solr 8 for profile collective.solr:default

2024-02-07 08:57 UTC, tisto approved these changes

2024-02-07 08:57 UTC, merged

2024-02-07 08:58 UTC, tisto commented
@remdub released with c.solr 9.2.3.